"""Test harness for the Fusion-Essentials MCP tools.

The tools under ``commands/mcpServer/tools/`` are written for a *live* Fusion
session: each one does ``import adsk.core`` and runs ``app =
adsk.core.Application.get()`` at module top level, and reaches Fusion geometry
through ``adsk.fusion``. To unit-test their pure logic outside Fusion we:

  1. Inject lightweight mock ``adsk`` modules into ``sys.modules`` BEFORE any
     tool is imported (so the module-top ``Application.get()`` succeeds).
  2. Load a single tool module in isolation — without running
     ``commands/__init__.py`` (which builds Fusion UI panels) or
     ``tools/__init__.py`` (which imports every tool module, most needing adsk).

``load_tool("model_inspect")`` does both and returns the module so a
test can call its ``handler(...)`` and private helpers directly.

The mocks here are deliberately small: they implement only what a tool actually
touches. Extend them as you add tests for more tools — that is the intended
workflow.
"""

import contextlib
import importlib.machinery
import importlib.util
import json
import os
import sys
import types
from unittest.mock import Mock

import pytest

# Measured adsk API facts, GENERATED by tests/live/measure_api.py against live Fusion. The
# mocks below are populated from these values - measurement, not hand-typed claims.
import live_api_facts as _api_facts


class _SourceLoader(importlib.machinery.SourceFileLoader):
    """Compile source bytes without consuming or producing disk bytecode."""

    def get_code(self, fullname):
        path = self.get_filename(fullname)
        return self.source_to_code(self.get_data(path), path)


class _SourceFinder:
    """Select source-only loading for the harness's repository import roots."""

    def __init__(self):
        roots = (os.path.join(COMMANDS_DIR, "mcpServer"), TOOLS_DIR,
                 os.path.join(REPO_ROOT, "tests", "live"))
        self.roots = tuple(os.path.normcase(os.path.realpath(p)) + os.sep for p in roots)

    def find_spec(self, fullname, path=None, target=None):
        spec = importlib.machinery.PathFinder.find_spec(fullname, path, target)
        if spec is not None and isinstance(spec.loader, importlib.machinery.SourceFileLoader):
            origin = os.path.normcase(os.path.realpath(spec.origin))
            if origin.startswith(self.roots):
                spec.loader = _SourceLoader(fullname, spec.origin)
                return spec
        return None


def _source_module(name, path, register=True):
    """Execute current source, discarding the direct module if its import fails."""
    spec = importlib.util.spec_from_file_location(name, path, loader=_SourceLoader(name, path))
    module = importlib.util.module_from_spec(spec)
    if register:
        sys.modules[name] = module
    try:
        spec.loader.exec_module(module)
    except BaseException:
        if register and sys.modules.get(name) is module:
            del sys.modules[name]
        raise
    return module


@contextlib.contextmanager
def _no_bytecode():
    """Use current repository source during harness imports and preserve other import behavior."""
    saved = sys.dont_write_bytecode
    finder = _SourceFinder()
    sys.meta_path.insert(0, finder)
    sys.dont_write_bytecode = True
    try:
        yield
    finally:
        if finder in sys.meta_path:
            sys.meta_path.remove(finder)
        sys.dont_write_bytecode = saved


REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
COMMANDS_DIR = os.path.join(REPO_ROOT, "commands")
TOOLS_DIR = os.path.join(COMMANDS_DIR, "mcpServer", "tools")


# ── the shared fakes ───────────────────────────────────────────────────────
#
# One module per family under tests/fakes/, re-exported here: a test says
# `from conftest import BRepBody` and reaches the same class the package defines. The repo root
# joins sys.path first because the generators run this file with tests/ alone on the path.
if REPO_ROOT not in sys.path:
    sys.path.insert(0, REPO_ROOT)

from tests.fakes.scaffold import _FakeObjectCollection, _NamedCollection  # noqa: E402
from tests.fakes.scaffold import _SimpleNamed, _StrictEnum, _Vertex  # noqa: E402
from tests.fakes.scaffold import _make_object_collection, entity_proxy, fusion_fake  # noqa: E402
from tests.fakes.geometry import Camera, Circle3D, Cone, Cylinder, FakeBoundingBox3D  # noqa: E402
from tests.fakes.geometry import FakeInfiniteLine3D, FakeMatrix3D, FakePoint  # noqa: E402
from tests.fakes.geometry import FakeValueInput, FakeVector3D, Line3D, Plane  # noqa: E402
from tests.fakes.geometry import Sphere, Torus, Viewport  # noqa: E402
from tests.fakes.geometry import camera_state, make_bbox  # noqa: E402
from tests.fakes.mesh import FakeMeshManager, FakeTriangleMeshCalculator  # noqa: E402
from tests.fakes.mesh import MeshBody, _FakeTriangleMesh, _MeshBodies  # noqa: E402
from tests.fakes.mesh import make_face_groups, make_mesh_manager  # noqa: E402
from tests.fakes.appearance import ColorProperty, FakeAppearance, FakeAppearances  # noqa: E402
from tests.fakes.appearance import FakeColor, FakeMaterialLibraries  # noqa: E402
from tests.fakes.appearance import FakeMaterialLibrary, _Properties  # noqa: E402
from tests.fakes.appearance import make_material_library  # noqa: E402
from tests.fakes.data_docs import FakeApplication, FakeData, FakeDataFile  # noqa: E402
from tests.fakes.data_docs import FakeDataFolder, FakeDataProject  # noqa: E402
from tests.fakes.data_docs import FakeDocumentReference, FakeDocuments  # noqa: E402
from tests.fakes.data_docs import FakeExportManager, FakeFusionDocument  # noqa: E402
from tests.fakes.data_docs import FakeProducts, FakeSelection, FakeSelections  # noqa: E402
from tests.fakes.data_docs import FakeUserInterface, _CloudArray, _ExportOptions  # noqa: E402
from tests.fakes.data_docs import make_data_tree, make_document_world  # noqa: E402
from tests.fakes.design import BRepBody, BRepEdge, BRepFace  # noqa: E402
from tests.fakes.design import FakeBaseFeature, FakeBaseFeatures, FakeFeature  # noqa: E402
from tests.fakes.design import FakeFeatures, FakeModelParameter, FakeOccurrence  # noqa: E402
from tests.fakes.design import FakeTimeline, FakeTimelineObject, FakeUnitsManager  # noqa: E402
from tests.fakes.design import FakeUserParameter, FakeUserParameters  # noqa: E402
from tests.fakes.design import MakeComp, MakeDesign, body_proxy, make_occurrence  # noqa: E402
from tests.fakes.design import make_placed_occurrence, make_source_document  # noqa: E402
from tests.fakes.design import make_timeline  # noqa: E402
from tests.fakes.sketch import FakeSketchPoint, Profile, Sketch, SketchCurves  # noqa: E402
from tests.fakes.sketch import make_sketch, make_sketch_curve, sketch_curves_edit  # noqa: E402
from tests.fakes.cam import FakeCAMFolder, FakeCAMParameter, FakeCAMParameters  # noqa: E402
from tests.fakes.cam import FakeMachine, FakeOperation, FakeSetup, FakeSetupInput  # noqa: E402
from tests.fakes.cam import FakeSetups, FakeTool, _InspMeasure, _InspPath  # noqa: E402
from tests.fakes.cam import _InspPoint, _Strategy, make_cam, make_cam_parameters  # noqa: E402
from tests.fakes.cam import make_gated_cam, make_inspection_cam, strategy_factory  # noqa: E402
from tests.fakes.cam import wcs_params  # noqa: E402
from tests.fakes.joints import CylindricalJointMotion, FakeAsBuiltJoint  # noqa: E402
from tests.fakes.joints import FakeContactSet, FakeJoint, FakeJointInput  # noqa: E402
from tests.fakes.joints import FakeJointOrigin, FakeJointOriginInput, FakeJoints  # noqa: E402
from tests.fakes.joints import FakeMotionLink, FakeMotionLinks, FakeRigidGroup  # noqa: E402
from tests.fakes.joints import FakeRigidGroups, FakeSnapshot, RevoluteJointMotion  # noqa: E402
from tests.fakes.joints import RigidJointMotion, SliderJointMotion, _MotionLimits  # noqa: E402
from tests.fakes.joints import make_joint  # noqa: E402
from tests.fakes.drawing import FakeCreateDrawingInput, FakeCustomSheetSize  # noqa: E402
from tests.fakes.drawing import FakeDocumentSettings, FakeDrawing  # noqa: E402
from tests.fakes.drawing import FakeDrawingDocument, FakeDrawingExportManager  # noqa: E402
from tests.fakes.drawing import FakeDrawingManager, FakeDrawingSketch  # noqa: E402
from tests.fakes.drawing import FakeDrawingSketches, FakeImages, FakeSheet  # noqa: E402
from tests.fakes.drawing import FakeSheets, FakeView, FakeViews, drawing_enum  # noqa: E402
from tests.fakes.drawing import drawing_value, install_drawing, make_drawing  # noqa: E402
from tests.fakes.drawing import make_drawing_session, make_drawing_views  # noqa: E402
from tests.fakes.pmi import FakePMIAnnotations, FakePMIDisplaySettings  # noqa: E402
from tests.fakes.pmi import FakePMIGeometricValue  # noqa: E402
from tests.fakes.pmi import FakePMIGeometricValueTolerance, FakePMIHoleThreadNote  # noqa: E402
from tests.fakes.pmi import FakePMIHoleThreadNoteInput, FakePMIHoleThreadNotes  # noqa: E402
from tests.fakes.pmi import FakePMILeaderLineNote, FakePMILeaderLineNoteInput  # noqa: E402
from tests.fakes.pmi import FakePMILeaderLineNotes, FakePMILineBreakSegment  # noqa: E402
from tests.fakes.pmi import FakePMISegmentVector, FakePMISymbolSegment  # noqa: E402
from tests.fakes.pmi import FakePMITextSegment, make_pmi_component  # noqa: E402
from tests.fakes.pmi import make_pmi_tolerance, make_pmi_value  # noqa: E402


# ── adsk mock installation ─────────────────────────────────────────────────

def install_mock_adsk():
    """Inject mock ``adsk`` / ``adsk.core`` / ``adsk.fusion`` into sys.modules.

    Returns ``(adsk, core, fusion)``. ``core``/``fusion`` are ``Mock`` objects,
    so any attribute a tool reads that we haven't explicitly modelled returns a
    child Mock rather than raising — convenient, but it means a test must assert
    on concrete values to actually pin behaviour down (a Mock is truthy and not
    ``None``). The type classes a tool uses for ``isinstance`` / ``.cast`` /
    ``type(x).__name__`` checks ARE modelled below, because those drive real
    branching.

    IDEMPOTENT: gen_manifest.py/gen_wiring.py call this again at their own import
    time so they work standalone (outside pytest) too - they rely on a second call
    being a no-op when a mock is already installed. A real re-install here would
    replace sys.modules['adsk'/'adsk.fusion'/...] with BRAND NEW objects; any module
    already loaded (e.g. _inputs.py, cached tool modules) keeps its OLD reference,
    so a later isinstance/.cast check would compare against the wrong generation
    of mock and fail in a way that depends on collection order.
    """
    existing = sys.modules.get("adsk")
    if (isinstance(existing, types.ModuleType)
            and sys.modules.get("adsk.fusion") is getattr(existing, "fusion", None)
            and sys.modules.get("adsk.core") is getattr(existing, "core", None)):
        return existing, existing.core, existing.fusion

    core = Mock()
    app = Mock()
    # Tools commonly tack `"active_document": app.activeDocument.name` onto a
    # payload that then gets json.dumps'd. A bare Mock().name is itself a Mock
    # (not JSON-serializable), so give the stock app a real string name. Tests
    # that care about document state override app.activeDocument explicitly.
    app.activeDocument.name = "TestDoc"
    app.version = "0.0.0-test"
    core.Application.get.return_value = app

    # CustomEventHandler is SUBCLASSED (task_manager's TaskEventHandler) - an auto-created Mock
    # attribute as a base class produces mock-flavored class machinery whose constructor cannot be
    # called normally, so the base must be a real (empty) class.
    core.CustomEventHandler = type("CustomEventHandler", (), {"__init__": lambda self: None})

    fusion = Mock()
    # Design.cast(product) fetches the active design. Model it as a
    # pass-through: whatever the test puts on app.activeProduct comes back.
    fusion.Design = Mock()
    fusion.Design.cast = Mock(side_effect=lambda x: x)

    # adsk.cam is needed by the CAM tools.
    cam = Mock()
    # Tools cast raw collection items with adsk.cam.Operation.cast(op) and skip
    # anything that casts to None. A bare Mock().cast returns a truthy Mock, which
    # would mask that filter; make cast a pass-through so a test's fake op (or a
    # real None) flows through unchanged.
    cam.Operation.cast = Mock(side_effect=lambda x: x)

    # adsk.drawing is needed by the drawing tools (drawing_create, drawing_export), which do
    # `import adsk.drawing` at module top - without it their import fails and the registry-wide
    # lints can't collect. A bare Mock covers the DrawingManager/DrawingExportManager surface.
    drawing = Mock()

    # Seed every measured enum family onto the mock namespaces, so comparison/branch code sees
    # the live integers without per-test hand-wiring. The drawing namespace gets the same strict
    # seeding, and its measured families now include the ones reached only by NAME through
    # _drawing_common.enum_value - SheetSizes, SheetOrientationTypes and DrawingStandardTypes - as
    # well as the ones referenced as literal adsk.drawing.<Family>: the harvester scans both, so
    # every family a drawing tool can read is measured here. Without that seeding they would be
    # fabricatable child Mocks, the exact silent-drop class the strict enums exist to refuse.
    ns = {"core": core, "fusion": fusion, "cam": cam, "drawing": drawing}
    for family, members in _api_facts.ENUMS.items():
        prefix, cls_name = family.split(".", 1)
        # A plain object, NOT the auto-created child Mock: a Mock invents any attribute asked of it,
        # so a member name that does not exist in live Fusion would return a fresh Mock, the tool
        # would set it on its input, and a test asserting `input.x == Enum.FabricatedName` would
        # compare that Mock to itself and PASS. _StrictEnum raises instead, like the live enum does.
        setattr(ns[prefix], cls_name, _StrictEnum(family, members))

    adsk = types.ModuleType("adsk")
    adsk.core = core
    adsk.fusion = fusion
    adsk.cam = cam
    adsk.drawing = drawing

    sys.modules["adsk"] = adsk
    sys.modules["adsk.core"] = core
    sys.modules["adsk.fusion"] = fusion
    sys.modules["adsk.cam"] = cam
    sys.modules["adsk.drawing"] = drawing
    return adsk, core, fusion


def load_tool(module_name):
    """Import one tool module in isolation, with mocked adsk already installed.

    Skips ``commands/__init__.py`` (Fusion UI side effects) and
    ``tools/__init__.py`` (imports every tool) by putting ``commands/`` on the
    path, importing only the cheap ``mcpServer`` + ``mcp_primitives`` packages,
    stubbing ``mcpServer.tools`` as an empty package, then spec-loading the
    single requested module so its ``from ..mcp_primitives ...`` relative
    imports resolve.

    Everything it loads runs under ``_no_bytecode()``: the tool module itself, the ``from . import
    _common``/``_inputs`` chain its body triggers, and the mcp_primitives packages.
    """
    with _no_bytecode():
        if COMMANDS_DIR not in sys.path:
            sys.path.insert(0, COMMANDS_DIR)

        import mcpServer                  # noqa: F401  empty __init__, cheap
        import mcpServer.mcp_primitives   # noqa: F401  adsk-free, cheap

        if "mcpServer.tools" not in sys.modules:
            tools_pkg = types.ModuleType("mcpServer.tools")
            tools_pkg.__path__ = [TOOLS_DIR]
            tools_pkg.__package__ = "mcpServer"
            sys.modules["mcpServer.tools"] = tools_pkg

        full_name = f"mcpServer.tools.{module_name}"
        # Reuse an already-loaded module instead of re-execing it into a NEW object. This is essential
        # for the shared substrate (_common/_inputs): tools do `from . import _common`, binding whatever
        # _common object is in sys.modules at load time. Re-execing _common would create a SECOND
        # _common — a tool loaded earlier keeps pointing at the first while the conftest
        # snapshot/restore (and a later test's patch) act on the second, so a patch or restore made
        # through one is invisible through the other. One canonical module per name keeps the seam
        # single-identity; each test wires its own per-test state onto that one object
        # (install()/monkeypatch), so reusing it is safe.
        if full_name in sys.modules:
            return sys.modules[full_name]
        module = _source_module(full_name, os.path.join(TOOLS_DIR, f"{module_name}.py"))
        # Record the seams of everything that import just put in sys.modules - the module itself and
        # the substrate its `from . import _common`/`_inputs` chain pulled in - while they still hold
        # their as-imported values. See _capture_pristine_seams.
        _capture_pristine_seams()
        return module


def stub_tool_module(monkeypatch, module_name, stub):
    """Swap ``mcpServer.tools.<module_name>`` for ``stub`` at both seams a sibling module is reached
    through. Returns the stub.

    The two seams belong to DIFFERENT import forms, and each patch serves exactly one of them:

    * ``from . import <module_name>`` - the form a handler's deferred delegate import uses
      (``data_get``) - resolves through the tools PACKAGE ATTRIBUTE. ``_handle_fromlist`` checks
      ``hasattr(package, name)`` FIRST and skips the submodule import entirely when it holds, so
      the ATTRIBUTE patch is what routes this form, in either order. A genuine import elsewhere
      binds that attribute too (``doc_get`` binds ``_data_read``; ``mesh_plane_cut`` binds
      ``_mesh_common``), and a sys.modules-only stub is then never consulted: the handler gets the
      real module and the stub goes silently inert while the test still passes or fails on what the
      real module does.
    * ``importlib.import_module(".<module_name>", __package__)`` at CALL time - what
      ``_sketch_detail._detail_engine`` and ``sys_get_api_doc``'s module walk do - reads SYS.MODULES and
      never the attribute, so the setitem is the only live seam for that shape.

    Both patches belong to ``monkeypatch``, so they unwind after the test - including the attribute,
    which is REMOVED again when the package did not carry it.
    """
    pkg = sys.modules.get("mcpServer.tools")
    if pkg is None:
        raise RuntimeError("stub_tool_module needs the tools package: call load_tool(...) first.")
    monkeypatch.setitem(sys.modules, f"mcpServer.tools.{module_name}", stub)
    monkeypatch.setattr(pkg, module_name, stub, raising=False)
    return stub


# Synthetic package root under which the REAL server modules are importable in tests.
_SERVER_PKG_ROOT = "feaddin"


def register_all_tools():
    """Load + register EVERY tool module against a fresh registry; return the registered Items.

    The one shared harness for wire-surface tests (shape + budget) - a single copy, so the two
    files cannot drift. Callers pair it with the conftest registry snapshot/restore (autouse),
    which undoes the global-registry mutation after each test."""
    names = [fn[:-3] for fn in sorted(os.listdir(TOOLS_DIR))
             if fn.endswith(".py") and not fn.startswith("_")]
    load_tool(names[0])                    # bootstraps the package path on first use
    from mcpServer.mcp_primitives import registry
    registry.reset_registry()
    for mod_name in names:
        mod = load_tool(mod_name)
        reg = getattr(mod, "register_tool", None)
        if callable(reg):
            reg()
    return registry.get_tools()


def load_tool_verify():
    """Import ``tests/live/tool_verify.py`` as a module and return it.

    The live sweep's tables (STEPS / EXCLUDED / PENDING) are plain data, so the offline lints read
    them without a Fusion - completeness against the registry, and which choices the steps send.
    One loader here rather than one per lint: the sweep's path moves as a unit."""
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "live", "tool_verify.py")
    with _no_bytecode():
        mod = _source_module("tool_verify", path, register=False)
    return mod


def is_write_tool(item):
    """True when a registered Item DECLARES itself a write - ``annotations.read_only is False``.

    A missing annotation and ``read_only is None`` both answer False: a tool that never declared its
    write status is not a write tool for a lint's purposes, and test_write_status_annotations is the
    gate that no such tool exists."""
    ann = item.primitive.annotations
    return ann is not None and ann.read_only is False


def load_mcp_server():
    """Import the REAL server/mcp_server.py (plus task_manager) for wire-level tests.

    mcp_server.py lives four packages deep in the add-in (``<addin>.commands.mcpServer.server``)
    and imports ``....lib.fusion360utils`` relatively, so it cannot be imported through the flat
    ``mcpServer`` package load_tool uses. This builds a synthetic package chain, stubs futil
    (the server only calls log/handle_error), and aliases the ALREADY-LOADED canonical
    ``mcpServer.mcp_primitives`` modules into the chain - the SAME module objects, so
    ``isinstance(item, Item)`` checks inside the server hold for Items built by tool modules.
    Idempotent: returns the cached module on repeat calls. Loads under ``_no_bytecode()``, like
    load_tool - the server modules are spec-loaded repo source too.
    """
    full_name = f"{_SERVER_PKG_ROOT}.commands.mcpServer.server.mcp_server"
    if full_name in sys.modules:
        return sys.modules[full_name]

    with _no_bytecode():
        install_mock_adsk()
        if COMMANDS_DIR not in sys.path:
            sys.path.insert(0, COMMANDS_DIR)
        importlib.import_module("mcpServer.mcp_primitives")

        def _pkg(name):
            mod = types.ModuleType(name)
            mod.__path__ = []
            sys.modules[name] = mod
            return mod

        _pkg(_SERVER_PKG_ROOT)
        lib_pkg = _pkg(f"{_SERVER_PKG_ROOT}.lib")
        futil_stub = types.ModuleType(f"{_SERVER_PKG_ROOT}.lib.fusion360utils")
        futil_stub.log = lambda *a, **k: None
        futil_stub.handle_error = lambda *a, **k: None
        lib_pkg.fusion360utils = futil_stub
        sys.modules[futil_stub.__name__] = futil_stub
        _pkg(f"{_SERVER_PKG_ROOT}.commands")
        _pkg(f"{_SERVER_PKG_ROOT}.commands.mcpServer")
        _pkg(f"{_SERVER_PKG_ROOT}.commands.mcpServer.server")

        for suffix in ("", ".item", ".tool", ".annotations", ".registry"):
            src = "mcpServer.mcp_primitives" + suffix
            importlib.import_module(src)
            sys.modules[f"{_SERVER_PKG_ROOT}.commands.mcpServer.mcp_primitives{suffix}"] = \
                sys.modules[src]
        importlib.import_module("mcpServer.version")
        sys.modules[f"{_SERVER_PKG_ROOT}.commands.mcpServer.version"] = sys.modules["mcpServer.version"]

        server_dir = os.path.join(COMMANDS_DIR, "mcpServer", "server")
        for mod_name in ("drawing_jobs", "task_manager", "mcp_server"):
            fq = f"{_SERVER_PKG_ROOT}.commands.mcpServer.server.{mod_name}"
            _source_module(fq, os.path.join(server_dir, f"{mod_name}.py"))
    return sys.modules[full_name]


# Pristine seam per tool module, captured ONCE the first time the module is seen — before any test
# patches it — so the autouse fixture can restore to it.
#
# A tool module reads the active design through one of a few module-level "seam" names: `app`
# (read by _common.design()), the imported-by-value `design`/`target_component`/`_design` helpers it
# calls bare, or `_data` (data tools). A test patches these on its OWN module object (e.g.
# `fl.target_component = lambda x: comp`, `mo.app = ...`). Because load_tool returns ONE canonical
# module object per tool for the whole session, such a patch LEAKS into the next test that uses the
# same module unless restored — producing order-dependent failures (the handler builds onto a stale
# fake). So the fixture restores these seam attrs on EVERY loaded tool module after each test, not
# just the substrate few. (`_design` covers the tools that bind a local `_design`.)
_PRISTINE_SEAMS = {}
_SEAM_ATTRS = ("design", "target_component", "_design", "app", "_data")


def _loaded_tool_modules():
    """Every currently-loaded `mcpServer.tools.*` module object (substrate + tools)."""
    return {name: mod for name, mod in sys.modules.items()
            if name.startswith("mcpServer.tools.") and mod is not None}


def _pristine_seam(key, mod):
    if key not in _PRISTINE_SEAMS:
        _PRISTINE_SEAMS[key] = {a: getattr(mod, a) for a in _SEAM_ATTRS if hasattr(mod, a)}
    return _PRISTINE_SEAMS[key]


def _capture_pristine_seams():
    """Record the as-imported seam values of every loaded tool module that has none recorded yet.

    Called from load_tool the moment a module is executed, and again at each test's SETUP. The
    load-time call is what makes the recording pristine: a module first imported inside a test BODY
    is already past that setup sweep, so without it the module's first recording happens at
    TEARDOWN - and a body that patched a seam imperatively (``mod.app = fake``) has the PATCHED
    value recorded as pristine and restored into the module for every test that follows."""
    for name, mod in _loaded_tool_modules().items():
        _pristine_seam(name, mod)


# Install mocks at collection time, before any test module imports a tool.
install_mock_adsk()


# Pristine snapshot of each adsk mock module's attribute namespace, captured ONCE right after install
# (before any test patches it). Tests routinely assign fake TYPE CLASSES and enum values onto these
# shared mocks — e.g. `adsk.fusion.BRepBody = SomeClass`, `adsk.fusion.MeshBody = ...`,
# `adsk.fusion.DesignTypes.ParametricDesignType = 1`, `adsk.core.Point3D.create = ...`. Because the
# mock modules are shared for the whole session, those assignments LEAK into later tests unless undone
# (a later test then isinstance-checks against the wrong class, or reads a stale enum, and fails only
# in certain orderings). Restoring each module's __dict__ to this snapshot after every test removes
# test-added attributes and reverts changed ones, making the suite order-independent.
def _snapshot_adsk_dicts():
    snap = {}
    for name in ("adsk.core", "adsk.fusion", "adsk.cam"):
        mod = sys.modules[name]
        # Shallow copy of the module-mock's own attribute dict, plus a shallow copy of each child
        # Mock's __dict__ one level down (that's where Type.cast / Type.create / Enum.MEMBER live).
        children = {}
        for attr, child in list(vars(mod).items()):
            cd = getattr(child, "__dict__", None)
            if isinstance(cd, dict):
                children[attr] = dict(cd)
        snap[name] = (dict(vars(mod)), children)
    return snap


def _restore_adsk_dicts(snap):
    for name, (top, children) in snap.items():
        mod = sys.modules[name]
        md = vars(mod)
        md.clear()
        md.update(top)
        for attr, cd in children.items():
            child = md.get(attr)
            chd = getattr(child, "__dict__", None)
            if isinstance(chd, dict):
                chd.clear()
                chd.update(cd)


_PRISTINE_ADSK = _snapshot_adsk_dicts()


@pytest.fixture(autouse=True)
def _restore_shared_adsk_mocks():
    """Snapshot-and-restore the mutable ``adsk`` mock attributes around every test.

    Tool tests install per-test behaviour by REASSIGNING attributes on the shared
    mocks — a cast/create callable (``adsk.fusion.Design.cast``,
    ``adsk.core.ValueInput.createByReal``), a fake type class
    (``adsk.fusion.BRepBody``), an enum member (``DesignTypes.*``). Because these
    live on module-level Mocks shared by the whole session, a reassignment would
    otherwise LEAK into later tests (e.g. a clobbered ``Design.cast`` pass-through
    makes an unrelated tool see no design at all). This autouse fixture records
    the originals before each test and puts them back after, keeping tests
    order-independent without per-file teardown.
    """
    # The whole adsk.core/fusion/cam mock namespace is snapshot/restored from _PRISTINE_ADSK (captured
    # once at install): test-assigned attributes are removed, reassigned ones reverted.
    # Tools that share _common.design()/target_component()/app (instead of a local _design()) are
    # tested by patching those on the _common module (the seam _inputs.py uses). Snapshot them at SETUP
    # and restore after, so a test's patch can't leak into a later test. _common is loaded lazily by
    # load_tool, so it may not exist yet on the very first tests — guard for that.
    # Capture pristine substrate seams at SETUP (before the test body patches them) - the backstop
    # under load_tool's own load-time capture, for a module that reached sys.modules another way.
    _capture_pristine_seams()
    # A few tests stub a tool's filesystem check by assigning `mod.os.path.isfile = lambda …`. Because
    # `mod.os` is the REAL os module, that mutates process-wide os.path and would leak into a later test
    # (e.g. a left-behind `isfile -> False` makes an unrelated upload report "file not found"). Snapshot
    # the real os.path predicates and restore them after the test.
    import os.path as _ospath
    _os_saved = [(_ospath, a, getattr(_ospath, a)) for a in ("isfile", "isdir", "exists")
                 if hasattr(_ospath, a)]
    # The registry SINGLETON is process-global, and several suite-wide tests populate it (a naming
    # lint's per-module reset+register loop, the wire-shape tests' full registration). Since
    # workspace_orient's pointer filter reads the live registry at call time, a leaked PARTIAL
    # registry makes pointer tests order-dependent. Snapshot the singleton pointer AND the instance's
    # tool dict at setup; restore both after - mirroring gen_manifest.collect()'s own guard.
    _reg_mod = sys.modules.get("mcpServer.mcp_primitives.registry")
    _reg_inst = _reg_mod._registry_instance if _reg_mod else None
    _reg_tools = dict(_reg_inst._tools) if _reg_inst is not None else None
    try:
        yield
    finally:
        if _reg_mod is not None:
            _reg_mod._registry_instance = _reg_inst
            if _reg_inst is not None:
                _reg_inst._tools.clear()
                _reg_inst._tools.update(_reg_tools)
        for _obj, _attr, _orig in _os_saved:
            setattr(_obj, _attr, _orig)
        _restore_adsk_dicts(_PRISTINE_ADSK)
        # load_tool returns ONE canonical object per tool module for the whole session, so a test that
        # patches a module-level seam (app/design/target_component/_design/_data) leaks into the next
        # test using that same module. Restore every loaded tool module's seam attrs to PRISTINE
        # (captured the first time the module is seen, before any patch — a per-test snapshot would
        # chain a prior test's patch forward and lose the original). This keeps the suite
        # order-independent without per-file teardown.
        for _name, _mod in _loaded_tool_modules().items():
            for attr, val in _pristine_seam(_name, _mod).items():
                setattr(_mod, attr, val)


@pytest.fixture
def bbox():
    """Factory: FakeBoundingBox3D from (min xyz, max xyz) in cm (Fusion's unit)."""
    return make_bbox


@fusion_fake(factory_for="MakeDesign")
def make_design(bodies=(), occurrences=(), tokens=None, comp=None, all_components=None,
                sketches=(), mesh_bodies=None, design_type=None, active_edit_object=None,
                timeline=None, user_parameters=None, all_parameters=None, compute_raises=None,
                snapshots=None, joints=None, as_built_joints=None, all_occurrences=None):
    """Build a standard FakeDesign. Use `comp=` to supply a tool-specific component (one carrying a
    fake `features`/`exportManager`/… surface); otherwise a plain MakeComp(bodies, occurrences).
    `timeline`/`user_parameters`/`all_parameters`/`compute_raises`/`snapshots` pass through to
    MakeDesign; `joints`/`as_built_joints`/`all_occurrences` to the component it builds."""
    if comp is None:
        comp = MakeComp(bodies=bodies, occurrences=occurrences, sketches=sketches,
                        mesh_bodies=mesh_bodies, joints=joints, as_built_joints=as_built_joints,
                        all_occurrences=all_occurrences)
    return MakeDesign(comp=comp, tokens=tokens, all_components=all_components,
                      design_type=design_type, active_edit_object=active_edit_object,
                      timeline=timeline, user_parameters=user_parameters,
                      all_parameters=all_parameters, compute_raises=compute_raises,
                      snapshots=snapshots)


def go_stale(*entities, attrs=("name", "parentComponent")):
    """Make `entities` stop answering their IDENTITY reads. MEASUREMENT reads (volume, faces,
    boundingBox, vertices) are left alone - those are what a post-mutation effect check counts on.

    This is a deliberate WORST CASE, not measured platform behaviour: a held target body was
    measured STILL answering parentComponent after a direct splitBodyFeatures.add. What it pins is
    that a handler must not DEPEND on a post-mutation identity read - a body the feature consumed
    outright has no such guarantee, and the dependency is invisible while every proxy stays alive.

    Call it from a feature fake's add(), after the canned effect lands: a payload key or an error
    clause that reads .name/.parentComponent AFTERWARDS then reads as unavailable, which is what
    forces the handler to capture it BEFORE."""
    for e in entities:
        for attr in attrs:
            # delattr, not a hasattr gate: a property-backed read that RAISES (BRepBody.isSolid
            # under solid_readable=False) makes hasattr answer False while the attribute is there.
            try:
                delattr(e, attr)
            except AttributeError:
                pass


# ── the dual-seam install (the test-plumbing convention) ────────────────────────────────────────
#
# A tool reads the active design through TWO seams:
#   • its own  `mod._common.design()` / `target_component()`  (and `mod.app`), and
#   • the input-kinds' `mod._inputs._common.design()` / `target_component()`  (BodyRef/PlaneRef/… use
#     _inputs, which has its OWN bound _common reference).
# Patching only the first is a silent trap: the handler resolves but the INPUT kind resolves against
# the wrong (or stale) design, so the test passes while testing the wrong thing. install() patches
# BOTH seams to the same design, making "patch both seams" structural instead of a remembered rule.

def install(mod, design, *, cast_design=True, object_collection=True):
    """Wire `design` into a tool module under both seams (see the dual-seam note above).

    Patches: mod.app (+ mod._common.app), and — when present — mod._inputs._common.design /
    target_component, plus adsk.fusion.Design.cast (pass-through for our design) and
    adsk.core.ObjectCollection.create (a minimal counted collection). All of these are reverted to
    pristine after each test by the autouse fixture, so the patch can't leak.

    Returns `design` for convenience (e.g. `design = install(mod, make_design(...))`).
    """
    import adsk.fusion
    import adsk.core

    comp = getattr(design, "rootComponent", None)
    target = lambda _d=None: getattr(design, "activeComponent", None) or comp

    mod.app = types.SimpleNamespace(activeProduct=design)
    # The tool's own seam (it imported _common; some import `target_component` bare too).
    if hasattr(mod, "_common"):
        mod._common.app = mod.app
        mod._common.design = lambda: design
        mod._common.target_component = target
    # The input-kinds seam (BodyRef/PlaneRef/AxisRef/GeometryHandle resolve through _inputs._common).
    if hasattr(mod, "_inputs") and hasattr(mod._inputs, "_common"):
        mod._inputs._common.design = lambda: design
        mod._inputs._common.target_component = target
    # A tool that imported `target_component`/`design` bare as module globals (e.g. model_fillet).
    if hasattr(mod, "target_component"):
        mod.target_component = target
    if hasattr(mod, "design"):
        mod.design = lambda: design

    if cast_design:
        adsk.fusion.Design.cast = lambda x: x if x is design or isinstance(x, MakeDesign) else None
    if object_collection:
        adsk.core.ObjectCollection.create = staticmethod(_make_object_collection)
    return design


def payload(result):
    """The success JSON body of a tool result; asserts it is NOT an error first."""
    assert result["isError"] is False, result
    return json.loads(result["content"][0]["text"])


def error_message(result):
    """Assert a tool result IS an error and return its message (for guard assertions)."""
    assert result["isError"] is True, result
    return result["message"]


def assert_no_active_design(mod, handler, **valid_kwargs):
    """A write/read tool that needs a design must return a clean 'no active design' error (not crash)
    when there is none. Point both seams at None, call the handler with otherwise-valid args, and
    assert the error mentions the design. Surfaces tools that skip the guard and NPE instead."""
    if hasattr(mod, "_common"):
        mod._common.design = lambda: None
    if hasattr(mod, "_inputs") and hasattr(mod._inputs, "_common"):
        mod._inputs._common.design = lambda: None
    res = handler(**valid_kwargs)
    msg = error_message(res).lower()
    assert "design" in msg or "document" in msg, res


def assert_unknown_units(handler, units_param="units", **valid_kwargs):
    """A tool taking a unit must reject an unknown one with a clear error (naming the unit), not
    silently scale by a bogus factor. Pass the other valid args; this sets units='furlong'."""
    res = handler(**{**valid_kwargs, units_param: "furlong"})
    msg = error_message(res).lower()
    assert "unit" in msg, res
