# Copyright (c) Fusion-Essentials contributors
# Dual-licensed under the MIT and Apache-2.0 licenses; see LICENSE-MIT and LICENSE-APACHE.

"""Generate tests/generated/ENFORCEMENT_MAP.md - the census of the enforcement layer itself.

One row per lint file (its own module docstring's opening sentence IS the invariant it guards),
plus the generator gate and a pointer to the typed seams. The map exists so that what is protected
is readable in one page - and what is NOT protected is conspicuous by absence instead of invisible
(an ungated agent-facing surface is invisible to both reviews and lints; this page is where its
absence shows). Regenerate with `py -3 tests/gen_all.py`; `--check` fails when stale.
"""

import ast
import os
import sys

TESTS = os.path.dirname(os.path.abspath(__file__))
LINTS = os.path.join(TESTS, "lints")
OUT = os.path.join(TESTS, "generated", "ENFORCEMENT_MAP.md")


def _first_sentence(docstring):
    """The docstring's opening sentence (to the first '. ' or line end), capped for the table."""
    if not docstring:
        return "(no module docstring)"
    text = " ".join(docstring.strip().split())
    for stop in (". ", ".\n"):
        if stop in text:
            text = text.split(stop, 1)[0] + "."
            break
    return text if len(text) <= 240 else text[:237] + "..."


def _lint_rows():
    rows = []
    for fn in sorted(os.listdir(LINTS)):
        if not (fn.startswith("test_") and fn.endswith(".py")):
            continue
        path = os.path.join(LINTS, fn)
        with open(path, "r", encoding="utf-8") as f:
            doc = ast.get_docstring(ast.parse(f.read()))
        rows.append((fn, _first_sentence(doc)))
    return rows


def _build():
    lines = [
        "# ENFORCEMENT_MAP - what is guarded, and by what",
        "",
        "GENERATED by tests/gen_enforcement.py - do not edit. Regenerate: `py -3 tests/gen_all.py`.",
        "",
        "Audience: agents (and the owner) opening a session cold. Every convention in this repo",
        "survives only as one of three enforcement forms - a LINT, a GENERATED surface, or a TYPED",
        "seam. This page is the census of all three. An agent-facing surface that appears in none",
        "of them is unguarded: treat that as a defect to ledger, not a freedom.",
        "",
        "## Lints (tests/lints/) - each row is the file's own stated invariant",
        "",
        "| Lint file | The invariant it guards |",
        "|---|---|",
    ]
    for fn, sentence in _lint_rows():
        lines.append(f"| {fn} | {sentence} |")
    lines += [
        "",
        "## Generated surfaces - gated by `py -3 tests/gen_all.py --check`",
        "",
        "Each generator rebuilds its artifact from the registry/source, so the artifact cannot",
        "drift from what it describes; test_generated_docs_current.py runs the check in the suite:",
        "",
    ]
    import gen_all
    for name in gen_all._GENERATORS:
        lines.append(f"- {name}.py" + (" (this page)" if name == "gen_enforcement" else ""))
    lines += [
        "",
        "## Typed seams - contracts enforced at construction, not by scanning",
        "",
        "- Input kinds: commands/mcpServer/tools/_inputs.py (the catalog table in tools/CLAUDE.md).",
        "- Postcondition kinds: commands/mcpServer/tools/_assert.py (capture -> mutate -> verify).",
        "- Verification declarations: commands/mcpServer/mcp_primitives/item.py (closed kinds;",
        "  every reference resolved by test_postconditions_declared.py).",
        "",
    ]
    return "\n".join(lines) + "\n"


def main():
    content = _build()
    check = "--check" in sys.argv[1:]
    if check:
        try:
            with open(OUT, "r", encoding="utf-8") as f:
                current = f.read()
        except OSError:
            current = None
        fresh = current is not None and current.replace("\r\n", "\n") == content
        if not fresh:
            print("ENFORCEMENT_MAP.md is stale - regenerate: py -3 tests/gen_all.py")
        else:
            print("ENFORCEMENT_MAP.md is up to date.")
        return fresh
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)
    print(f"wrote {OUT}")
    return True


if __name__ == "__main__":
    sys.exit(0 if main() else 1)
