# Copyright (c) Fusion-Essentials contributors
# Dual-licensed under the MIT and Apache-2.0 licenses; see LICENSE-MIT and LICENSE-APACHE.

"""Generate tests/generated/STRATEGY_COMPETENCE.md - which toolpath families this server can drive.

One row per strategy the CAM setups offer: the geometry kind it takes, the tool kind, and either the
sweep beat that proves it cuts or the message the platform answered with when it could not. The rows
come from verify_acts_census.CENSUS, whose PROVEN entries name beats the live sweep runs, so a
strategy cannot be published as driveable without a receipt row behind it. Regenerate with
`py -3 tests/gen_all.py`; `--check` fails when stale.
"""

import importlib.util
import os
import sys

TESTS = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(TESTS, "generated", "STRATEGY_COMPETENCE.md")


def _census():
    """The census module, loaded from tests/live the way the offline lints load the sweep."""
    live = os.path.join(TESTS, "live")
    if live not in sys.path:
        sys.path.insert(0, live)
    path = os.path.join(live, "verify_acts_census.py")
    spec = importlib.util.spec_from_file_location("verify_acts_census", path)
    mod = importlib.util.module_from_spec(spec)
    old, sys.dont_write_bytecode = sys.dont_write_bytecode, True
    try:
        spec.loader.exec_module(mod)
    finally:
        sys.dont_write_bytecode = old
    return mod


def _tally(rows, verdict):
    return sum(1 for r in rows if r[1] == verdict)


def _build():
    census = _census()
    rows = sorted(census.CENSUS)
    lines = [
        "# STRATEGY_COMPETENCE - the toolpath families, and which of them are driven",
        "",
        "GENERATED by tests/gen_strategies.py - do not edit. Regenerate: `py -3 tests/gen_all.py`.",
        "",
        "Audience: an agent picking a machining strategy. 'proven' means a live sweep beat creates",
        "that strategy, gives it the geometry kind named here, generates it, and reads machining",
        "time above zero back off the operation - hasToolpath reads true on an EMPTY toolpath, so it",
        "is never the oracle. 'measured' means that same reading was taken by hand, with no receipt",
        "row behind it. 'created' means a beat lands the operation and reads its name back, and",
        "nothing here measures a toolpath - the family has none. 'refused' means the create tool",
        "declines it before mutating anything, and 'skipped' carries the message the platform",
        "answered with; nothing in either column is a guess about cause. Create with",
        "cam_create_operation, aim with cam_select_geometry.",
        "",
        f"Counts: {_tally(rows, census.PROVEN)} proven, {_tally(rows, census.MEASURED)} measured, "
        f"{_tally(rows, census.CREATED)} created, {_tally(rows, census.REFUSED)} refused, "
        f"{_tally(rows, census.SKIPPED)} skipped, {len(rows)} strategies.",
        "",
        "| Strategy | Verdict | Geometry kind (cam_select_geometry) | Tool | Proven on / the measured reason |",
        "|---|---|---|---|---|",
    ]
    for name, verdict, geometry, tool, where in rows:
        lines.append(f"| {name} | {verdict} | {geometry} | {tool} | {where} |")
    lines += [
        "",
        "## Neighbours - what separates a family from the one beside it",
        "",
        "Measured with cam_compare_operations on two operations of the SAME tool, and asserted by",
        "the sweep beat that publishes them. An operation's own 'strategy' PARAMETER reads a",
        "different vocabulary from the strategies list cam_create_operation takes, so both are here.",
        "",
        "| Pair | 'strategy' parameter | Carried by the first alone | Carried by the second alone |",
        "|---|---|---|---|",
    ]
    for _a_op, a, a_id, a_only, _b_op, b, b_id, b_only in census.NUANCE:
        lines.append(f"| {a} vs {b} | {a_id} vs {b_id} | {', '.join(a_only)} | "
                     f"{', '.join(b_only)} |")
    lines += [
        "",
        "### Measured by hand - the CAM overview samples",
        "",
        "Read with cam_compare_operations on Autodesk's CAM overview samples. No beat creates these",
        "operations, so nothing here has a receipt row behind it, and 'd' in a value is the cutter",
        "diameter.",
        "",
        "| Pair | What separates them |",
        "|---|---|",
    ]
    for first, second, differs in census.MEASURED_NUANCE:
        lines.append(f"| {first} vs {second} | {differs} |")
    lines.append("")
    return "\n".join(lines) + "\n"


def main():
    content = _build()
    if "--check" in sys.argv[1:]:
        try:
            with open(OUT, "r", encoding="utf-8") as f:
                current = f.read()
        except OSError:
            current = None
        fresh = current is not None and current.replace("\r\n", "\n") == content
        print("STRATEGY_COMPETENCE.md is up to date." if fresh
              else "STRATEGY_COMPETENCE.md is stale - regenerate: py -3 tests/gen_all.py")
        return fresh
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)
    print(f"wrote {OUT}")
    return True


if __name__ == "__main__":
    sys.exit(0 if main() else 1)
