# Copyright (c) Fusion-Essentials contributors
# Dual-licensed under the MIT and Apache-2.0 licenses; see LICENSE-MIT and LICENSE-APACHE.

"""The infrastructure every fake family stands on: the declaration decorator, the strict enum, the
counted collection, the entity proxy and the object collection."""

# Measured adsk API facts, GENERATED by tests/live/measure_api.py against live Fusion. The
# fakes below are populated from these values - measurement, not hand-typed claims.
import live_api_facts as _api_facts


# -- provenance declarations on the shared fakes ----------------------------

def fusion_fake(live_type=None, facts=(), factory_for=None, scenario_double=None):
    """Declare what a shared fake stands for and which measured rows back it.

    METADATA ONLY: this records ``__fusion_fake__`` and hands the object back untouched, so no
    fake's behaviour depends on being declared.

    ``live_type`` is the adsk type the fake impersonates, named by its SHAPES key - the same key
    test_fake_shapes_exist.py sweeps the fake's public members against - and ``facts`` are the
    measure_api row ids that measured what the fake encodes. A def that CONSTRUCTS a declared fake
    names it with ``factory_for``, so no builder of declared fakes sits outside the inventory.
    ``scenario_double`` classifies a double that impersonates no live type at all, its string being
    the reason.

    test_fake_shapes_exist.py resolves every id against measure_api.ROWS, so a row renamed or
    dropped from the registry turns each fake citing it red.
    """
    declaration = {"live_type": live_type, "facts": tuple(facts), "factory_for": factory_for,
                   "scenario_double": scenario_double}

    def declare(obj):
        obj.__fusion_fake__ = declaration
        return obj
    return declare


class _StrictEnum:
    """One measured adsk enum family. Accessing a member that was NOT measured against live Fusion
    raises AttributeError, exactly as the live enum does. Tools legitimately probe with
    getattr(Enum, name, None) for version-dependent members, and that still returns the default."""

    def __init__(self, family, members):
        self._family = family
        for member, value in members.items():
            setattr(self, member, value)

    def __getattr__(self, name):
        known = ", ".join(sorted(k for k in vars(self) if not k.startswith("_")))
        raise AttributeError(
            f"adsk.{self._family} has no member '{name}' - it does not exist in Fusion "
            f"{_api_facts.FUSION_VERSION}. Measured members: {known}. If '{name}' is real, add a "
            "measurement row to tests/live/measure_api.py and regenerate live_api_facts.py.")

    def __repr__(self):
        return f"<measured adsk.{self._family}>"


@fusion_fake(scenario_double="a harness affordance, not a stand-in for any live type: it publishes "
                             "no member of its own and delegates every read to the fake it wraps, "
                             "so it has no member surface to sweep and nothing to measure")
class _EntityProxy:
    """See ``entity_proxy``. Deliberately holds no state of its own - reads and writes both go to the
    one underlying entity, so only object IDENTITY differs."""

    def __init__(self, obj):
        object.__setattr__(self, "_obj", obj)

    def __getattr__(self, name):
        return getattr(object.__getattribute__(self, "_obj"), name)

    def __setattr__(self, name, value):
        setattr(object.__getattribute__(self, "_obj"), name, value)

    def __delattr__(self, name):
        delattr(object.__getattribute__(self, "_obj"), name)


@fusion_fake(factory_for="_EntityProxy")
def entity_proxy(obj):
    """A DISTINCT Python object for the same entity, every read delegated to `obj` (measured:
    entity-proxy-token-shared - six wrappers of one entity share one token and no two are the
    same object, so identity never answers an is-it-the-same question)."""
    return _EntityProxy(obj)


@fusion_fake(live_type="BRepBodies", facts=("shape-dump-design-world", "brepbodies-protocol",
                                           "item-oor-brepbodies", "item-oor-sketches"))
class _NamedCollection:
    """Counted collection (Fusion's count/item(i)) with itemByName lookup (None on a miss),
    iterable - the measured live protocol (see live_api_facts; NamedViews' raise-on-miss is the
    known exception, see test_view_set).

    `raises` is the collection that will not enumerate AT ALL - count, item, itemByName and
    iteration each throw that message, which is not the same answer as an empty walk. A test flips
    `_raises` on the instance to break the reads mid-flight. `item_raises` is the NARROWER state -
    the walk counts, but reaching for a member throws - which is what a collection whose length
    survives a stale read while its items do not answers."""
    def __init__(self, items=(), raises=None, item_raises=None):
        self._items = list(items)
        self._raises = raises
        self._item_raises = item_raises

    def _live(self):
        if self._raises:
            raise RuntimeError(self._raises)

    @property
    def count(self):
        self._live()
        return len(self._items)

    def item(self, i):
        self._live()
        if self._item_raises:
            raise RuntimeError(self._item_raises)
        if 0 <= i < len(self._items):
            return self._items[i]
        if _api_facts.BEHAVIOR["collection_item_out_of_range_raises"]:
            # live, the raise can escape try/except entirely - bound-check against .count
            raise RuntimeError("3 : invalid argument index")
        return None

    def itemByName(self, name):
        self._live()
        for it in self._items:
            if getattr(it, "name", None) == name:
                return it
        if _api_facts.BEHAVIOR["item_by_name_none_on_miss"]:
            return None
        raise RuntimeError("3 : invalid argument name")

    def __iter__(self):
        self._live()
        return iter(self._items)


def _absent_member(name):
    """A class attribute standing for one the live type does NOT have: hasattr answers False and a
    reach for it raises AttributeError, which is what an absent member does - not a method that
    refuses."""
    def _missing(self):
        raise AttributeError(name)
    return property(_missing)


class _Vertex:
    def __init__(self, point):
        self.geometry = point


class _SimpleNamed:
    def __init__(self, name):
        self.name = name


@fusion_fake(live_type="ObjectCollection",
             facts=("shape-dump-design-world", "objectcollection-protocol",
                    "objectcollection-duplicate-add-takes"))
class _FakeObjectCollection:
    """ObjectCollection: add() answers a bool; a duplicate add is TAKEN live (measured: True twice,
    count 2), so the False here is `refuse`'s own silent rejection, never a de-dup."""
    def __init__(self, refuse=()):
        self._items = []
        self._refuse = list(refuse)
    def add(self, x):
        if any(x is r for r in self._refuse):
            return False
        self._items.append(x)
        return True
    @property
    def count(self):
        return len(self._items)
    def __iter__(self):
        return iter(self._items)
    def item(self, i):
        return self._items[i]


@fusion_fake(factory_for="_FakeObjectCollection")
def _make_object_collection(refuse=()):
    return _FakeObjectCollection(refuse)
