# Copyright (c) Fusion-Essentials contributors
# Dual-licensed under the MIT and Apache-2.0 licenses; see LICENSE-MIT and LICENSE-APACHE.

"""MCP building block: create a new sketch on an origin/construction plane OR on an existing planar
face. The sketch's world FRAME is published on the way in - the map its later coordinates ride on.
"""

import adsk.core

from ..mcp_primitives.tool import Tool
from ..mcp_primitives.item import Item, Verification
from ..mcp_primitives.registry import register
from ._common import apply_rename, error, ok, safe, target_component
from ._sketch_detail import _plane_name, frame_space_note, sketch_world_frame
from . import _common
from . import _inputs

app = adsk.core.Application.get()

_ON_FACE = _inputs.GeometryHandle("on_face", require="planar_face")

# The plane sketch_create builds on. PlaneRef owns every reference form and every refusal.
_PLANE = _inputs.PlaneRef("plane", default="xy",
                          description="Ignored with 'on_face'.")


def handler(plane: str = "xy", name: str = "", on_face: str = "") -> dict:
    """Create a new sketch on an origin/construction plane OR on an existing planar face (on_face)."""
    design = _common.design()
    if not design:
        return error("No active design. Create or open a document first (see doc_new).")

    # on_face (a GeometryHandle input) takes precedence - closes the 'sketch on a face' gap.
    # The input-kind resolves+validates the handle to a PLANAR face (or returns a clear error),
    # so this handler never has to re-implement that logic.
    if (on_face or "").strip():
        face, ferr = _ON_FACE.resolve(on_face)
        if ferr:
            # A construction-plane NAME lands here (find_geometry never returns plane handles), and
            # the generic stale-handle error would misdirect. Point at the 'plane' parameter instead.
            named_plane, _ = _PLANE.resolve(on_face.strip())
            if named_plane is not None:
                return error(f"'on_face' got '{on_face.strip()}', which is a construction PLANE name, "
                             "not a face handle. Pass it as plane='" + on_face.strip() + "' instead - "
                             "'on_face' takes a planar-FACE handle from find_geometry.")
            return error(ferr)
        planar, desc = face, f"face {on_face[:12]}..."
    else:
        values, perr = _inputs.resolve_inputs([_PLANE], {"plane": plane})
        if perr:
            return perr
        # The kind resolves a blank 'plane' through its own default, so the label names that default
        # rather than the empty string the caller sent.
        given = (plane or "").strip() or _PLANE.default
        planar, desc = values["plane"], f"plane '{given}'"

    try:
        sketch = target_component(design).sketches.add(planar)
    except Exception as e:
        return error(f"Failed to create sketch on {desc}: {e}")
    if not sketch:
        return error(f"Sketch creation returned nothing on {desc}.")

    final_name, rename_warning = apply_rename(sketch, name)

    # On a face (and on xz/yz) the sketch's (0,0) is NOT the face centre and its axes need not line
    # up with world, so the frame is what lets a caller place geometry by computed coords.
    frame = safe(lambda: sketch_world_frame(sketch, design))

    payload = {
        "created": True,
        "sketch_name": final_name,
        "on": desc,
        "plane": _plane_name(sketch),
        "frame": frame,
        "note": ("Draw on it with sketch_add_geometry (target this sketch by name). "
            + frame_space_note(frame)),
    }
    if rename_warning:
        payload["rename_warning"] = rename_warning
    return ok(payload)


TOOL_DESCRIPTION = (
    "Create a sketch on a plane or a planar face; draw on it with sketch_add_geometry."
)
tool = (
    Tool.create_simple(name="sketch_create", description=TOOL_DESCRIPTION)
    .add_input_property(*_PLANE.as_property())
    .add_input_property("name", {"type": "string"})
    # on_face's schema (incl. its 'needs a planar-face handle from find_geometry' contract note) is
    # generated by the InputKind itself - single source of truth for resolution + schema + contract.
    .add_input_property(_ON_FACE.name, _ON_FACE.schema())
    .strict_schema()
)
item = Item.create_tool_item(
    tool=tool, write="write", handler=handler, run_on_main_thread=True,
    verification=Verification(
        kind="effect", rung="value",
        evidence_test="tests/unit/test_sketch_create.py::TestCreateRenameDisclosure"
                      "::test_a_swallowed_rename_is_disclosed_beside_the_actual_name"))


def register_tool():
    register(item)
