# Copyright (c) Fusion-Essentials contributors
# Dual-licensed under the MIT and Apache-2.0 licenses; see LICENSE-MIT and LICENSE-APACHE.
"""Exercise offline declaration comparison and its evidence boundaries."""

import copy
import hashlib
import json

import pytest

import api_change_report as report
import gen_api_surface

OLD = '''# This file was automatically generated by SWIG.
raise RuntimeError("Declarations must never execute")
class Options:
    Enabled = 1
    def _get_width(self) -> "float":
        """Width of the item."""
    width = property(_get_width)
    def create(self, count: "int" = 1) -> "bool":
        """Create an item."""
    def obsolete(self):
        pass
'''
NEW = OLD.replace('Enabled = 1', 'Enabled = 2').replace('count: "int" = 1', 'count: "int" = 2')
NEW = NEW.replace('"""Create an item."""', '"""This is a preview and is not officially supported."""')
NEW = NEW.replace('    width = property(_get_width)', '    def _set_width(self, value: "float"):\n        pass\n    width = property(_get_width, _set_width)')
NEW = NEW.replace('def obsolete(self):', 'def replacement(self):') + '\nclass Added:\n    pass\n'


@pytest.fixture
def captures(tmp_path):
    def capture(name, source, namespace='fusion'):
        folder = tmp_path / name
        folder.mkdir()
        (folder / f'{namespace}.py').write_bytes(source.encode('utf-8'))
        return report.snapshot(folder, name)
    return capture


def test_reports_added_removed_signature_writability_enum_and_support(captures):
    before, after = captures('before', OLD), captures('after', NEW)
    changes = {c['symbol']: c for c in report.compare(before, after)['changes']}
    assert changes['adsk.fusion.Options.obsolete']['change'] == 'removed'
    assert changes['adsk.fusion.Options.replacement']['change'] == 'added'
    assert changes['adsk.fusion.Added']['change'] == 'added'
    width = changes['adsk.fusion.Options.width']
    assert width['before']['writable'] is False and width['after']['writable'] is True
    assert changes['adsk.fusion.Options.Enabled']['after']['literal'] == 2
    create = changes['adsk.fusion.Options.create']['after']['overloads'][0]
    assert create['signature']['arguments'][0]['default'] == '2'
    assert create['mentions_preview'] is True and create['mentions_unsupported'] is True


def test_unavailable_namespace_never_becomes_symbol_removal(captures, tmp_path):
    before = captures('before', OLD)
    folder = tmp_path / 'before'
    (folder / 'cam.py').write_text('class MissingNamespaceType:\n    pass\n', encoding='utf-8')
    before = report.snapshot(folder, 'before')
    after = captures('after', OLD)
    delta = report.compare(before, after)
    assert delta['namespaces_unavailable_in_after'] == ['adsk.cam']
    assert delta['changes'] == []
    reverse = report.compare(after, before)
    assert reverse['namespaces_unavailable_in_before'] == ['adsk.cam']
    assert reverse['changes'] == []


@pytest.mark.parametrize('mismatch', ['format', 'representation', 'namespace_scope'])
def test_incompatible_comparisons_are_refused(captures, mismatch):
    before, after = captures('before', OLD), captures('after', OLD)
    if mismatch == 'format':
        after['format'] = 'older-format'
    elif mismatch == 'representation':
        after['modules']['adsk.fusion']['representation'] = 'python'
    else:
        after['namespace_scope'].append('adsk.future')
        after['unavailable_namespaces'].append('adsk.future')
    after['content_sha256'] = report.content_hash(after)
    with pytest.raises(ValueError, match='format|representation|scopes'):
        report.compare(before, after)


def test_provenance_hashes_original_bytes_and_preserves_deployment_identity(tmp_path):
    folder = tmp_path / 'webdeploy/pre-production/abc123/Api/Python/packages/adsk'
    folder.mkdir(parents=True)
    raw = b'\xef\xbb\xbf' + OLD.replace('\n', '\r\n').encode('utf-8')
    (folder / 'fusion.py').write_bytes(raw)
    data = report.snapshot(folder, 'reported-build')
    assert data['modules']['adsk.fusion']['sha256'] == hashlib.sha256(raw).hexdigest()
    assert data['modules']['adsk.fusion']['path'] == str((folder / 'fusion.py').resolve())
    assert data['provenance']['webdeploy_path'] == {'channel': 'pre-production', 'directory_id': 'abc123'}
    assert data['provenance']['build_label'] == 'reported-build'
    assert data['provenance']['build_label_source'].startswith('caller-supplied')
    assert data['unavailable_namespaces'] == ['adsk.core', 'adsk.cam', 'adsk.drawing', 'adsk.sim', 'adsk.electron', 'adsk.volume']
    assert 'api_change_report.py' in data['provenance']['scanner_sha256']
    assert gen_api_surface.scan_module(str(folder / 'fusion.py'), 'fusion')[0]['fusion.Options'] == ['Enabled', 'create', 'obsolete', 'width']


def test_modified_snapshot_and_overwriting_are_refused(captures, tmp_path):
    data = captures('bindings', OLD)
    path = tmp_path / 'snapshot.json'
    report.write_json(path, data)
    original = path.read_bytes()
    with pytest.raises(FileExistsError):
        report.write_json(path, {})
    assert path.read_bytes() == original
    changed = copy.deepcopy(data)
    changed['modules']['adsk.fusion']['classes'].clear()
    with pytest.raises(ValueError, match='content hash'):
        report.compare(data, changed)
    loaded, provenance = report.load_snapshot(path)
    assert loaded == data
    assert provenance['sha256'] == hashlib.sha256(original).hexdigest()


@pytest.fixture
def source_repo(tmp_path):
    repo = tmp_path / 'repo'
    files = {
        'commands/mcpServer/tools/model_demo.py': 'from . import _demo\ndef register_tool():\n    pass\n',
        'commands/mcpServer/tools/model_unrelated.py': 'def register_tool():\n    pass\n',
        'commands/mcpServer/tools/_demo.py': 'def apply(obj):\n    return obj.width\n',
        'tests/unit/test_model_demo.py': 'def test_width_effect():\n    pass\n',
        'tests/live/verify_acts_model.py': 'ROWS = [("model_demo", {}, "ok", None)]\n',
        'tests/live/evals/scenarios/S_Demo.md': 'Exercise model_demo.\n',
    }
    for relative, text in files.items():
        path = repo / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding='utf-8')
    return repo


def test_helper_matches_and_checks_are_only_syntactic_candidates(captures, source_repo):
    before, after = captures('before', OLD), captures('after', NEW)
    data = report.add_impacts(report.compare(before, after), source_repo)
    width = next(c for c in data['changes'] if c['symbol'].endswith('.width'))
    assert width['candidate_tools'] == [{
        'tool': 'model_demo', 'classification': 'syntactic_candidate',
        'source_matches': [{'file': 'commands/mcpServer/tools/_demo.py', 'line': 2, 'via': 'local_import'}],
    }]
    mapping = data['impact_mapping']
    assert mapping['classification'] == 'syntactic_candidate'
    assert 'Empty matches do not prove absence of impact' in mapping['limitations']
    cases = mapping['candidate_acceptance_cases']['model_demo']
    assert cases['classification'] == 'syntactic_candidate'
    assert [c['kind'] for c in cases['cases']] == ['unit_test', 'live_row', 'eval_tool_mention']
    assert cases['cases'][0]['case'] == 'test_width_effect'
    assert 'tests/live/verify_acts_model.py' in mapping['source_sha256']
    assert 'model_unrelated' not in mapping['candidate_acceptance_cases']


def test_cli_diff_preserves_input_bytes_and_emits_provenance(captures, source_repo, tmp_path, capsys):
    before, after = captures('before', OLD), captures('after', NEW)
    a, b, output = (tmp_path / name for name in ('a.json', 'b.json', 'impact.json'))
    report.write_json(a, before)
    report.write_json(b, after)
    original = a.read_bytes(), b.read_bytes()
    assert report.main(['diff', str(a), str(b), '--repo', str(source_repo), '--out', str(output)]) == 0
    data = json.loads(output.read_text(encoding='utf-8'))
    assert data['before_snapshot']['path'] == str(a.resolve())
    assert data['after_snapshot']['modules']['adsk.fusion']['sha256'] == after['modules']['adsk.fusion']['sha256']
    assert data['summary'] == {'added': 2, 'removed': 1, 'changed': 3}
    assert (a.read_bytes(), b.read_bytes()) == original
    assert json.loads(capsys.readouterr().out)['output'] == str(output.resolve())


def test_python_overloads_setter_type_and_symbolic_constants_are_preserved(captures):
    source = '''class Demo:
    Enabled = _native.Demo_Enabled
    @overload
    def make(self, value: int): ...
    @overload
    def make(self, value: str): ...
    @property
    def width(self) -> float: ...
    @width.setter
    def width(self, value: float): ...
'''
    data = captures('python', source)
    cls = data['modules']['adsk.fusion']['classes']['adsk.fusion.Demo']
    assert data['modules']['adsk.fusion']['representation'] == 'python'
    assert len(cls['members']['make']['overloads']) == 2
    assert cls['members']['width']['setter_signature']['arguments'][0]['type'] == 'float'
    enabled = cls['members']['Enabled']
    assert enabled['expression'] == '_native.Demo_Enabled'
    assert enabled['literal_available'] is False


def test_property_assignment_controls_exposure_even_when_helpers_remain(captures):
    before = captures('before', NEW)
    readonly = NEW.replace('property(_get_width, _set_width)', 'property(fget=_get_width, fset=None)')
    after = captures('after', readonly)
    changes = report.compare(before, after)['changes']
    width = next(c for c in changes if c['symbol'] == 'adsk.fusion.Options.width')
    assert width['before']['writable'] is True and width['after']['writable'] is False
    assert width['after']['readable'] is True
    assert 'setter_signature' not in width['after']
    unexposed = captures('unexposed', NEW.replace('    width = property(_get_width, _set_width)\n', ''))
    removed = report.compare(before, unexposed)['changes']
    assert next(c for c in removed if c['symbol'].endswith('.width'))['change'] == 'removed'
