"""The live_api_facts wiring: the generated measured facts actually POPULATE the mocks.

``tests/live_api_facts.py`` is generated by ``tests/live/measure_api.py`` from a
fully-PASSING run against live Fusion. These tests pin the consumption seams: every measured enum
family is seeded onto the mock adsk modules, and the shared fakes read their behavior flags at
CALL time - so regenerating the file changes fake behavior without touching conftest.
"""

import pytest

import adsk.cam
import adsk.core
import adsk.drawing
import adsk.fusion

import live_api_facts
from conftest import FakeVector3D, _NamedCollection


class TestEnumSeeding:
    def test_every_measured_enum_family_is_seeded_on_the_mock_modules(self):
        ns = {"core": adsk.core, "fusion": adsk.fusion, "cam": adsk.cam,
              "drawing": adsk.drawing}
        assert live_api_facts.ENUMS, "generated facts carry no enum families"
        for family, members in live_api_facts.ENUMS.items():
            prefix, cls_name = family.split(".", 1)
            cls = getattr(ns[prefix], cls_name)
            for member, value in members.items():
                assert getattr(cls, member) == value, f"{family}.{member} not seeded"

    def test_seeded_values_are_ints_not_child_mocks(self):
        assert isinstance(adsk.fusion.DesignTypes.ParametricDesignType, int)
        assert isinstance(adsk.cam.OperationStates.NoToolpathOperationState, int)


class TestBehaviorFlagsConsumedAtCallTime:
    def test_fake_vector_zero_normalize_follows_the_measured_flag(self, monkeypatch):
        measured = live_api_facts.BEHAVIOR["vector3d_normalize_true_on_zero"]
        assert FakeVector3D(0, 0, 0).normalize() is bool(measured)
        monkeypatch.setitem(live_api_facts.BEHAVIOR,
                            "vector3d_normalize_true_on_zero", not measured)
        assert FakeVector3D(0, 0, 0).normalize() is bool(not measured)

    def test_collection_item_out_of_range_follows_the_measured_flag(self, monkeypatch):
        coll = _NamedCollection(["a"])
        assert live_api_facts.BEHAVIOR["collection_item_out_of_range_raises"] is True
        with pytest.raises(RuntimeError):
            coll.item(5)
        monkeypatch.setitem(live_api_facts.BEHAVIOR,
                            "collection_item_out_of_range_raises", False)
        assert coll.item(5) is None
